### PR TITLE
Fixed bootVolume name bug

### LINKED ISSUE #2260: Cluster provisioning fails when BootVolume Name is specified
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Added the following to the VPCMachineTemplate spec and tried to provision a cluster with multiple worker nodes:
```
bootVolume:
        name: boot-vol
        sizeGiB: 20
```

The control-plane and one worker node came up successfully but the other one is failing with the following error in the controller logs:
```
"Reconciler error" err="failed to reconcile VSI for IBMVPCMachine default/anshuman-test-cluster-md-0-579cn-42htf: Volume with name \"boot-vol\" already exists" control
ler="ibmvpcmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="IBMVPCMachine" IBMVPCMachine="default/anshuman-test-cluster-md-0-579cn-42htf" namespace="default" name="anshuman-test-cluster-md-0
-579cn-42htf" reconcileID="ae4f44c7-12e6-4160-ac54-cec7b11b583d"
```

**What did you expect to happen:**
Cluster gets provisioned

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by anshuman-agarwala**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2260 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fixed bug where adding volume name with multiple worker nodes would cause errors due to unique volume name constraint.
```

### CODE REVIEW

File: cloud/scope/machine.go [hunk 1]
```diff
@@ -427,7 +427,7 @@ func (m *MachineScope) volumeToVPCVolumeAttachment(volume *infrav1beta2.VPCVolum
 	}
 
 	if volume.Name != "" {
-		bootVolume.Volume.Name = core.StringPtr(volume.Name)
```
Comment (Prajyot-Parab) [inline cloud/scope/machine.go:430]: `volume.Name` spec is intended to be assigned to `bootVolume.Volume.Name` or `bootVolume.Name` ?
what would be the value of `bootVolume.Volume.Name` post this change?
```
If unspecified, the name will
	// be a hyphenated list of randomly-selected words.
```
is this the flow expectation?

**Comment by Prajyot-Parab** [comment]
@anshuman-agarwala Please update the release note in description.

File: cloud/scope/machine.go (hunk 1 above)
Comment (anshuman-agarwala) [reply cloud/scope/machine.go:430]: Yes, the boot volume name is expected to be random. This is required because when we add a volume name to the bootvolume the machine creation fails as each machine tries to create and mount a volume with the same name in their shared workspace which is not supported by IBMCloud.

**Review by Prajyot-Parab — COMMENTED** [review]
/lgtm

**Review by Karthik-K-N — COMMENTED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
