### PR TITLE
Fix priority between network and DHCP server

### LINKED ISSUE #2159: Priority to network name or DHCP server name while creating the DHCP server
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
Address the issue described here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1933#issuecomment-2510515529

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:
Fix priority between network and DHCP server
Do not allow to set both network and DHCP server details which will create conflict while creating new DHCP server on whether to use network name or DHCP server name

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2159 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fix priority between network and DHCP server
```

### CODE REVIEW

File: api/v1beta2/ibmpowervscluster_webhook_test.go [hunk 1]
```diff
@@ -68,6 +68,36 @@ func TestIBMPowerVSCluster_create(t *testing.T) {
...
+			name: "Should error if both Network id and DHCP are set",
+			powervsCluster: &IBMPowerVSCluster{
+				Spec: IBMPowerVSClusterSpec{
+					ServiceInstanceID: "capi-si-id",
+					Network: IBMPowerVSResourceReference{
+						ID: ptr.To("capi-net-id"),
+					},
+					DHCPServer: &DHCPServer{
+						Name: ptr.To("capi-dhcp"),
+					},
```
Comment (Karthik-K-N) [inline api/v1beta2/ibmpowervscluster_webhook_test.go:96]: May lets also add test with network name - dhcp id , network id -dhcp id combination?

**Review by Karthik-K-N — COMMENTED** [review]
https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/c4171f21acc320fdfe17b812c98be908653134f7/cloud/scope/powervs_cluster.go#L870, This comment needs an update as now we are not allowing to set both network and DHCP details in spec.

**Comment by dharaneeshvrd** [comment]
Addressed the comments, ptal @Karthik-K-N

**Review by Karthik-K-N — COMMENTED** [review]
Do you think is there a way to handle/inform about this scenario, Correct me if my understanding is wrong.

What if user sets network.Name="abc" the network "abc" does not exist in cloud. I think our controller will create a DHCP network `DHCPSERVERabc_Private`. Now user has set "abc" as network in spec but actually its `DHCPSERVERabc_Private`

**Comment by Karthik-K-N** [comment]
True, Thats the only thing we can do, along with that should we update spec.Network.Name with the newly created DHCP network name? will that be allowed?

**Comment by dharaneeshvrd** [comment]
> should we update spec.Network.Name with the newly created DHCP network name? will that be allowed?

Can you please elaborate this? Do you mean to update the spec once we created the DHCP network? Just wondering since we won't follow that generally right!

**Comment by Karthik-K-N** [comment]
> > should we update spec.Network.Name with the newly created DHCP network name? will that be allowed?
> 
> Can you please elaborate this? Do you mean to update the spec once we created the DHCP network? Just wondering since we won't follow that generally right!

True we wont follow it, Just thinking.

**Comment by Karthik-K-N** [comment]
Or else how about strict validation like ID, when network.Name is set it should exist or else return error?

Most of the time we ommit network field and controller will autocreate the resource so it wont be a breaking change.

**Comment by dharaneeshvrd** [comment]
Yeah that might be an option if we consider that field only for non DHCP networks. Anyway we are validating with that intention only. But only concern is that it would deviate from the other places on how we treat the name field of a resource.

**Comment by Karthik-K-N** [comment]
> Yeah that might be an option if we consider that field only for non DHCP networks. Anyway we are validating with that intention only. But only concern is that it would deviate from the other places on how we treat the name field of a resource.

True that, Though the use case is very minimal, I am not so sure about showing wrong info about network name in spec. 

May be lets discuss this in the community meeting and we can either go with that or keep as it is and add note like now.

**Comment by Karthik-K-N** [comment]
Discussed about it in the CAPIBM community meeting, We will keep the flow as is and not add a validation for network.Name like network.ID.

Need to setup another meeting to decide on how to allow  users to create DHCP or static network.

**Review by Karthik-K-N — COMMENTED** [review]
/lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm
