### PR TITLE
make SERVICE_ENDPOINT variable optional

### LINKED ISSUE #836: clusterctl init expects SERVICE_ENDPOINT variable
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
```shell
% clusterctl init --infrastructure ibmcloud
Fetching providers
Error: failed to get provider components for the "ibmcloud" provider: failed to perform variable substitution: value for variables [SERVICE_ENDPOINT] is not set. Please set the value using os environment variables or the clusterctl config file
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Assign default value to SERVICE_ENDPOINT to make it optional variable.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #836

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
make SERVICE_ENDPOINT variable optional
```

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
/cc @mkumatag 

Is there a way to verify the same without cutting out a release?

File: pkg/endpoints/endpoints.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ var (
 // ParseServiceEndpointFlag parses the command line flag of service endpoint in the format ${ServiceRegion}:${ServiceID1}=${URL1},${ServiceID2}=${URL2...}
 // returning a list of ServiceEndpoint.
 func ParseServiceEndpointFlag(serviceEndpoints string) ([]ServiceEndpoint, error) {
-	if serviceEndpoints == "" {
+	if serviceEndpoints == "" || serviceEndpoints == "\"\"" {
```
Comment (mkumatag) [inline pkg/endpoints/endpoints.go:60]: This will be `""` instead of empty string which is not great idea, I prefer setting some minimal value fed or think about some other way to fix this!

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: pkg/endpoints/endpoints.go (hunk 1 above)
Comment (Prajyot-Parab) [reply pkg/endpoints/endpoints.go]: Fixed - default value `none`

**Review by mkumatag — APPROVED** [review]
/lgtm
