### PR TITLE
Fix inbound rule to allow only APIServerPort

### LINKED ISSUE #964: Default VPC security group has inbound rule to allow all ipv4
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Currently I can see default security group of VPC has inbound rule to allow all ipv4.
Its being updated from here https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/cloud/scope/cluster.go#L159

Is there any specific reason for this?

**What did you expect to happen:**

Ideally we should have inbound rule to allow whatever port we required to access the cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Fix inbound rule to allow only APIServerPort

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #964 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fix inbound rule to allow only APIServerPort
```

### CODE REVIEW

File: cloud/scope/cluster.go [hunk 1]
```diff
@@ -186,8 +186,10 @@ func (s *ClusterScope) updateDefaultSG(sgID string) error {
 	options.SetSecurityGroupID(sgID)
 	options.SetSecurityGroupRulePrototype(&vpcv1.SecurityGroupRulePrototype{
 		Direction: core.StringPtr("inbound"),
-		Protocol:  core.StringPtr("all"),
+		Protocol:  core.StringPtr("tcp"),
 		IPVersion: core.StringPtr("ipv4"),
+		PortMin:   core.Int64Ptr(6443),
```
Comment (mkumatag) [inline cloud/scope/cluster.go:191]: What if the exposed api server port is other than 6443?

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: cloud/scope/cluster.go (hunk 1 above)
Comment (Prajyot-Parab) [reply cloud/scope/cluster.go]: Fixed, ptal.

**Review by mkumatag — APPROVED** [review]
/lgtm
