### PR TITLE
fix panic error when scope obj is not yet initialized

### LINKED ISSUE #1396: IBMPowerVSCluster runtime error while creating a cluster: invalid memory address or nil pointer dereference.
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
- Create a PowerVS cluster with incorrect `IBMPOWERVS_SERVICE_INSTANCE_ID`. Cluster will be in provisioning state + the CAPIBM controller will repeatedly crash with panic runtime error.

Error:
```
[manager] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[manager] 	panic: runtime error: invalid memory address or nil pointer dereference
```

**What did you expect to happen:**
- Error handling should be done properly with no panic + runtime error causing codebase crash

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- fix panic error when scope obj is not yet initialized

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1396 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
fix panic error when scope obj is not yet initialized
```

### CODE REVIEW

File: cloud/scope/powervs_cluster.go [hunk 1]
```diff
@@ -150,6 +150,9 @@ func NewPowerVSClusterScope(params PowerVSClusterScopeParams) (scope *PowerVSClu
 
 // PatchObject persists the cluster configuration and status.
 func (s *PowerVSClusterScope) PatchObject() error {
+	if s == nil {
```
Comment (mkumatag) [inline cloud/scope/powervs_cluster.go:153]: are you sure it is for the `s` ? may be it is for the patchHelper field!

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: cloud/scope/powervs_cluster.go (hunk 1 above)
Comment (Prajyot-Parab) [reply cloud/scope/powervs_cluster.go:153]: @mkumatag yes `s` obj is nil
```
code:
fmt.Println("obj:--- ", s)

log:
[manager] obj:---  <nil>
```

Comment (mkumatag) [reply cloud/scope/powervs_cluster.go:153]: but from this is getting triggered, we need to block in the calling method.

Comment (mkumatag) [reply cloud/scope/powervs_cluster.go:153]: I think this is being called in the defer method, lets handle it there, e.g: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/983675a6acf3ff5f3d3bf7dbf94d40a86d268939/controllers/ibmpowervsmachine_controller.go#L142

Comment (Prajyot-Parab) [reply cloud/scope/powervs_cluster.go]: Yes fixed it.

Comment (mkumatag) [reply cloud/scope/powervs_cluster.go]: but we need to handle such situation in every defer calls

Comment (Prajyot-Parab) [reply cloud/scope/powervs_cluster.go]: @mkumatag you meant as a preventative measure right (since we have not came across that issue in other defer calls but yes I agree there is always a possibility)

Comment (Prajyot-Parab) [reply cloud/scope/powervs_cluster.go]: Updated.

**Review by mkumatag — APPROVED** [review]
/lgtm
