### PR TITLE
Fix revive package name conventions

### LINKED ISSUE #2458: Fix golangci-lint issue surrounding `avoid meaningless package names`
With the recent bump of golangci-linter version from 2.1.6 to 2.3.1, Under the `revive` linter, a certain rule - `avoid meaningless package names` has been skipped to allow the version update through https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/2457. 

To fix this issue, one may need to remove the `'var-naming: avoid meaningless package names - rule` under `exclusions` from the [.golangci.yml](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/.golangci.yml#117) file from the repository root and run the linter locally with `make lint` command. Please make appropriate changes to suppress the issue.

A couple of those identified in the previous runs are: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-ibmcloud/2451/pull-cluster-api-provider-ibmcloud-test/1952628794493767680
```
cmd/capibmadm/utils/utils.go:18:9: var-naming: avoid meaningless package names (revive)
package utils
               ^
pkg/cloud/services/utils/paging.go:17:9: var-naming: avoid meaningless package names (revive)
package utils
               ^
util/util.go:17:9: var-naming: avoid meaningless package names (revive)
package util
               ^
```

### PR DESCRIPTION
**Pull request by mayuka-c**
**What this PR does / why we need it**:
This PR addresses the revive package naming convention issue

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2458

**Special notes for your reviewer**:
/kind cleanup
/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
This PR is for fixing the linting issue.

**Release note**:

```release-note
Fix revive package name conventions
```

**Validation**

After running `make lint`

`
INFO [runner] linters took 5.793821833s with stages: goanalysis_metalinter: 5.771707958s 
0 issues.
INFO File cache stats: 3 entries of total size 17.5KiB 
INFO Memory: 72 samples, avg is 1216.4MB, max is 2175.7MB 
INFO Execution took 7.086381416s  `

### CODE REVIEW

File: pkg/cloud/services/pagingutils/paging.go
Comment (Prajyot-Parab) [inline pkg/cloud/services/pagingutils/paging.go:1]: missing supporting `doc.go`

File: cmd/capibmadm/pointer/pointer.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
+/*
+Copyright 2023 The Kubernetes Authors.
```
Comment (Prajyot-Parab) [inline cmd/capibmadm/pointer/pointer.go:2]:
```suggestion
Copyright 2025 The Kubernetes Authors.
```

File: cloud/scope/powervs_cluster.go [hunk 2]
```diff
@@ -49,16 +49,16 @@ import (
 	v1beta1patch "sigs.k8s.io/cluster-api/util/deprecated/v1beta1/patch" //nolint:staticcheck
 
 	infrav1 "sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta2"
+	genUtil "sigs.k8s.io/cluster-api-provider-ibmcloud/genutil"
```
[the remark this answers is not in the document]
Comment (mayuka-c) [reply cloud/scope/powervs_cluster.go]: Done, I have removed the named import. Thanks!

File: pkg/cloud/services/pagingutils/paging.go
Comment (mayuka-c) [reply pkg/cloud/services/pagingutils/paging.go:1]: Since there was only single file, I had added the package comment in the same file. Now I have created doc.go and moved the package comment there

File: cmd/capibmadm/pointer/pointer.go (hunk 1 above)
Comment (mayuka-c) [reply cmd/capibmadm/pointer/pointer.go]: Done thanks

File: genutil/doc.go [hunk 3]
```diff
@@ -14,5 +14,5 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
-// Package utils implements utils code.
-package utils
+// Package genutil implements general utility code.
+package genutil
```
Comment (mkumatag) [inline genutil/doc.go:18]: let us avoid having anything in the root folder, see if we can move this under pkg to internal

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: pkg/cloud/services/pagingutils/paging.go
Comment (mkumatag) [reply pkg/cloud/services/pagingutils/paging.go:1]: Most of the code under `pkg/cloud/services/` are related to the one talking to the cloud, can we move this to somewhere else like `pkg/utils` and rename fix the naming aspect.

**Review by mkumatag — CHANGES_REQUESTED** [review]
overall LGTM with a minor comment

**Comment by mayuka-c** [comment]
> overall LGTM with a minor comment

I have moved the pagining utils under pkg/ dir. Thanks!

File: pkg/cloud/services/pagingutils/paging.go
Comment (mayuka-c) [reply pkg/cloud/services/pagingutils/paging.go:1]: I have moved the pagining utils under pkg/ dir. Thanks!

**Review by mkumatag — APPROVED** [review]
/lgtm
