### PR TITLE
VPC e2e mtu fix

### LINKED ISSUE #1058: vpc e2e prow job is failing
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-capi-provider-ibmcoud-e2e-vpc

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
**What this PR does / why we need it**:
- Fix to set desired MTU value for VPC e2e runs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1058 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fix to set desired MTU value for VPC e2e runs
```

### CODE REVIEW

File: hack/kind-network-fix.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+set -o errexit
+set -o nounset
+set -o pipefail
+
+set -x
+
+docker network create \
+  --ipv6 \
+  --subnet=fc00:f853:ccd:e793::/64 \
```
Comment (mkumatag) [inline hack/kind-network-fix.sh:25]: why ipv6 network?

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: hack/kind-network-fix.sh (hunk 1 above)
Comment (Prajyot-Parab) [reply hack/kind-network-fix.sh:25]: The default network created by capi e2e framework has ipv6 enabled, so trying to replicate the same state. (do you want to explore the possibility of dropping it if not needed?)

Comment (mkumatag) [reply hack/kind-network-fix.sh:25]: I tried creating the network on my local machine and see that it is allocating the ipv4 address as well, its just that they are using this additional ipv6 as well but not really sure where this will be used in the test

$ docker network inspect hack-mak
```json
[
    {
        "Name": "hack-mak",
        "Id": "b37e176ba2d81852ce9fa6186074f3ded6140c280595583495b5410819e3f435",
        "Created": "2023-03-02T09:49:00.560307961Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                },
                {
                    "Subnet": "fc00:f853:ccd:e794::/64"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.driver.mtu": "1480"
        },
        "Labels": {}
    }
]
```

**Review by mkumatag — APPROVED** [review]
lets merge this and see the behaviour of the CI post merging this PR.

/lgtm
