### PR TITLE
Validate machine spec values

### LINKED ISSUE #596: IBMPowerVSMachine failed to create with message failed to convert memory() to float64
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**

machine spec:
```yaml
% k get IBMPowerVSMachine example-92sz6 -n clusters-example -o=yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSMachine
metadata:
  annotations:
    cluster.x-k8s.io/cloned-from-groupkind: IBMPowerVSMachineTemplate.infrastructure.cluster.x-k8s.io
    cluster.x-k8s.io/cloned-from-name: example
    hypershift.openshift.io/nodePoolPlatformMachineTemplate: '{"template":{"spec":{"serviceInstanceID":"634f8562-566b-4f53-a056-3fa2ccb0d105","imageRef":{"name":"410.84.202201251004-0"},"network":{"id":"243d1c0e-c821-4a16-9ef5-8afdcdaf04fc"}}}}'
  creationTimestamp: "2022-03-21T09:49:19Z"
  finalizers:
  - ibmpowervsmachine.infrastructure.cluster.x-k8s.io
  generation: 1
  labels:
    cluster.x-k8s.io/cluster-name: example-vgd9r
    example-vgd9r-example-example: example-vgd9r-example-example
    machine-template-hash: "3423079655"
  name: example-92sz6
  namespace: clusters-example
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Machine
    name: example-vgd9r-example-example-78674cfb99-m2pbz
    uid: e905d714-fc36-45c4-bf31-5fa2cfc822ed
  resourceVersion: "63222081"
  uid: 3c602b1f-33d1-43ab-910a-a0d5be8e11a4
spec:
  imageRef:
    name: 410.84.202201251004-0
  network:
    id: 243d1c0e-c821-4a16-9ef5-8afdcdaf04fc
  serviceInstanceID: 634f8562-566b-4f53-a056-3fa2ccb0d105
status:
  conditions:
  - lastTransitionTime: "2022-03-21T10:09:23Z"
    message: failed to convert memory() to float64
    reason: InstanceProvisionFailed
    severity: Error
    status: "False"
    type: InstanceReady
  region: eu-de
  zone: eu-de-2
```

error log:
```
I0321 10:21:18.165436       1 ibmpowervsmachine_controller.go:171] controllers/IBMPowerVSMachine "msg"="Reconciling IBMPowerVSMachine" "cluster"="example-vgd9r" "ibmpowervsmachine"={"Namespace":"clusters-example","Name":"example-92sz6"}
E0321 10:21:20.134979       1 ibmpowervsmachine_controller.go:198] controllers/IBMPowerVSMachine "msg"="unable to create instance" "error"="failed to convert memory() to float64" "cluster"="example-vgd9r" "ibmpowervsmachine"={"Namespace":"clusters-example","Name":"example-92sz6"}
E0321 10:21:20.135485       1 controller.go:317] controller/ibmpowervsmachine "msg"="Reconciler error" "error"="failed to reconcile VSI for IBMPowerVSMachine clusters-example/example-92sz6: failed to convert memory() to float64" "name"="example-92sz6" "namespace"="clusters-example" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="IBMPowerVSMachine"
```

**What did you expect to happen:**
IBMPowerVSMachine creation shouldn't fail.

**Anything else you would like to add:**
this is with 0.2 version

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Validate machine spec memory/processors values.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #596 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Validate machine spec values.
```

### CODE REVIEW

File: api/v1beta1/ibmpowervsmachine_webhook.go [hunk 1]
```diff
@@ -127,3 +133,17 @@ func (r *IBMPowerVSMachine) validateIBMPowerVSMachineImage() *field.Error {
 	}
 	return nil
 }
+
+func (r *IBMPowerVSMachine) validateIBMPowerVSMachineMemory() *field.Error {
+	if res := validateIBMPowerVSResourceValues(r.Spec.Memory); !res {
```
Comment (mkumatag) [inline api/v1beta1/ibmpowervsmachine_webhook.go:138]: memory is always in int format

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: api/v1beta1/common.go [hunk 2]
```diff
@@ -60,6 +65,26 @@ func validateIBMPowerVSResourceReference(res IBMPowerVSResourceReference, resTyp
...
+		if strings.Contains(strings.ToLower(resValue), vt) {
+			return false
+		}
+	}
+	if val, err := strconv.ParseFloat(resValue, 64); err != nil || val <= 0 {
+		return false
+	}
+	return true
+}
+
```
Comment (mkumatag) [inline api/v1beta1/common.go:87]: This doesn't look clean, wondering if we can use regex marker for this one `+kubebuilder:validation:Pattern`, one another point this allows like -12.345 as well, which is not a valid number.

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: api/v1beta1/ibmpowervsmachine_types.go [hunk 3]
```diff
@@ -62,6 +62,7 @@ type IBMPowerVSMachineSpec struct {
 
 	// Processors is Number of processors allocated.
 	// +optional
+	// +kubebuilder:validation:Pattern=^[0-9]\.[0-9][0-9]$
```
Comment (mkumatag) [inline api/v1beta1/ibmpowervsmachine_types.go:65]: I don't think its covering all the cases, ptal - https://regex101.com/r/qYe78r/1

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: api/v1beta1/common.go [hunk 4]
```diff
@@ -60,6 +65,26 @@ func validateIBMPowerVSResourceReference(res IBMPowerVSResourceReference, resTyp
...
+func validateIBMPowerVSProcessorValues(resValue string) bool {
+	valueTypes := [...]string{"nan", "inf"}
+	for _, vt := range valueTypes {
+		if strings.Contains(strings.ToLower(resValue), vt) {
+			return false
+		}
+	}
```
Comment (mkumatag) [inline api/v1beta1/common.go:81]: does it really any sense now after the regex?

File: api/v1beta1/common.go [hunk 5]
```diff
@@ -60,6 +65,26 @@ func validateIBMPowerVSResourceReference(res IBMPowerVSResourceReference, resTyp
...
 }
 
+func validateIBMPowerVSMemoryValues(resValue string) bool {
+	if val, err := strconv.ParseUint(resValue, 10, 64); err != nil || val < 2 {
+		return false
+	}
+	return true
+}
+
+func validateIBMPowerVSProcessorValues(resValue string) bool {
```
Comment (mkumatag) [inline api/v1beta1/common.go:75]: lets add some UT around this function

File: api/v1beta1/common.go [hunk 6]
```diff
@@ -60,6 +65,26 @@ func validateIBMPowerVSResourceReference(res IBMPowerVSResourceReference, resTyp
 	return true, nil
 }
 
+func validateIBMPowerVSMemoryValues(resValue string) bool {
```
Comment (mkumatag) [inline api/v1beta1/common.go:68]: lets add some UT around this function

**Review by mkumatag — CHANGES_REQUESTED** [review]

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve
