### PR TITLE
Fix IBMPowerVSImage deletion

### LINKED ISSUE #538: Deleting the IBMPowerVSCluster object is not deleting the underneath IBMPowerVSImage
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
1. Deploy a Cluster, IBMPowerVSCluster and IBMPowerVSImage spec
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-powervs-1
  name: ibm-powervs-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ibm-powervs-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: IBMPowerVSCluster
    name: ibm-powervs-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSImage
metadata:
  name: ibmpowervsimage-sample
spec:
  clusterName: "ibm-powervs-1"
  serviceInstanceID: 97ff60d4-5b60-4a3d-bb28-34aedc603bf3
  bucket: "power-oss-bucket"
  object: "capibm-powervs-centos-treams8-1-22-4.ova.gz"
  region: "us-south"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: IBMPowerVSCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ibm-powervs-1
  name: ibm-powervs-1
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 158.175.162.5
    port: 6443
  network:
    name: mkumatag-capi-net
  serviceInstanceID: 97ff60d4-5b60-4a3d-bb28-34aedc603bf3
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ibm-powervs-1-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
          - 192.168.151.5
          - 158.175.162.5
      controlPlaneEndpoint: 192.168.151.5:6443
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    files:
      - content: |
          apiVersion: v1
          kind: Pod
          metadata:
            creationTimestamp: null
            name: kube-vip
            namespace: kube-system
          spec:
            containers:
            - args:
              - manager
              env:
              - name: vip_arp
                value: "true"
              - name: vip_interface
                value: "env2"
              - name: port
                value: "6443"
              - name: vip_cidr
                value: "29"
              - name: cp_enable
                value: "true"
              - name: cp_namespace
                value: kube-system
              - name: vip_ddns
                value: "false"
              - name: svc_enable
                value: "true"
              - name: vip_leaderelection
                value: "true"
              - name: vip_leaseduration
                value: "5"
              - name: vip_renewdeadline
                value: "3"
              - name: vip_retryperiod
                value: "1"
              - name: vip_address
                value: "192.168.151.5"
              image: docker.io/plndr/kube-vip:v0.3.7
              imagePullPolicy: Always
              name: kube-vip
              resources: {}
              securityContext:
                capabilities:
                  add:
                  - NET_ADMIN
                  - NET_RAW
                  - SYS_TIME
              volumeMounts:
              - mountPath: /etc/kubernetes/admin.conf
                name: kubeconfig
            hostNetwork: true
            volumes:
            - hostPath:
                path: /etc/kubernetes/admin.conf
              name: kubeconfig
          status: {}
        owner: root:root
        path: /etc/kubernetes/manifests/kube-vip.yaml
        permissions: "0744"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          provider-id: ibmpowervs://ibm-powervs-1/'{{ v1.local_hostname }}'
        name: '{{ v1.local_hostname }}'
    joinConfiguration:
      discovery:
        bootstrapToken:
          apiServerEndpoint: 192.168.151.5:6443
          caCertHashes: []
          token: ""
          unsafeSkipCAVerification: false
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
          provider-id: ibmpowervs://ibm-powervs-1/'{{ v1.local_hostname }}'
        name: '{{ v1.local_hostname }}'
    preKubeadmCommands:
      - hostname "{{ v1.local_hostname }}"
      - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
      - echo "127.0.0.1   localhost" >>/etc/hosts
      - echo "127.0.0.1   {{ v1.local_hostname }}" >>/etc/hosts
      - echo "{{ v1.local_hostname }}" >/etc/hostname
    useExperimentalRetryJoin: true
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: IBMPowerVSMachineTemplate
      name: ibm-powervs-1-control-plane
  replicas: 1
  version: v1.22.5
```
2. Delete the Cluster spec
```
k delete cluster ibm-powervs-1
```
3. After step 1 and 2, IBMPowerVSImage is not getting deleted 

**What did you expect to happen:**
Even `IBMPowerVSImages` should get deleted but it is not,

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
Fix IBMPowerVSImage deletion
- Delete IBMPowerVSImage on deletion of IBMPowerVSCluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #538 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
few minor comments, otherwise lgtm

File: controllers/ibmpowervsimage_controller.go [hunk 1]
```diff
@@ -97,6 +97,15 @@ func (r *IBMPowerVSImageReconciler) Reconcile(ctx context.Context, req ctrl.Requ
 func (r *IBMPowerVSImageReconciler) reconcile(ctx context.Context, cluster *v1beta1.IBMPowerVSCluster, imageScope *scope.PowerVSImageScope) (ctrl.Result, error) {
 	controllerutil.AddFinalizer(imageScope.IBMPowerVSImage, v1beta1.IBMPowerVSImageFinalizer)
 
+	// Create new labels section for IBMPowerVSImage metadata if nil
+	if imageScope.IBMPowerVSImage.Labels == nil {
+		imageScope.IBMPowerVSImage.Labels = make(map[string]string)
+	}
+
+	if len(imageScope.IBMPowerVSImage.Labels[clusterv1.ClusterLabelName]) == 0 {
```
Comment (mkumatag) [inline controllers/ibmpowervsimage_controller.go:105]: you can use the golang ok statement to check the map entry existence, ref: https://stackoverflow.com/questions/2050391/how-to-check-if-a-map-contains-a-key-in-go

**Review by mkumatag — CHANGES_REQUESTED** [review]

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve
