### PR TITLE
Use multiple zones in case of multiple subnets

### LINKED ISSUE #1779: Multiple subnet creation fails when zone is not specified
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
If zone it not specified while creating multiple subnets, second subnet creation will fail as the default address prefix is already assigned to the first subnet.
Spec:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
metadata:
  annotations:
    powervs.cluster.x-k8s.io/create-infra: "true"
  labels:
    cluster.x-k8s.io/cluster-name: capi-test-amulya
  name: capi-test-amulya
  namespace: default
spec:
  loadBalancers:
  - name: capi-test-amulya-loadbalancer
  - name: capi-test-amulya-loadbalancer-1
  resourceGroup:
    name: ibm-hypershift-dev
  serviceInstance:
    name: capi-test-amulya-serviceInstance
  transitGateway:
    name: capi-test-amulya-transitgateway
  vpc:
    name: capi-test-amulya-vpc
    region: eu-es
  vpcSubnets:
  - name: capi-test-amulya-vpcsubnet
  - name: capi-test-amulya-vpcsubnet-1
  zone: mad02
```

Creation fails with
```
"error creating vpc subnet" err="Subnet CIDR 10.251.0.0/18 conflicts with existing subnet: 02w7-c247a3e9-c9d0-4717-a878-96edd68059c4
```

**What did you expect to happen:**
While creating multiple subnets, if subnet zone is missing from spec, don't proceed and instead throw an error.

**Anything else you would like to add:**
We can add a check to validate the spec before proceeding with cluster creation.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Shilpa-Gokul**
**What this PR does / why we need it**:
Currently when there are multiple subnets specified, it uses the first available vpcZone for all subnets by default and as a result, there is a clash in the CIDR. Hence added logic to use the subsequent vpcZones for the subnets.

If there are multiple subnets provided than the available vpcZones, the zones are selected based on round robin method.

This PR contains change to use vpcSubnetIPAddressCount, where when two subnets are to be created in the same zone, the subnets are created with the next available address prefix based on the vpcSubnetIPAddressCount.
Taking one of the below examples for reference

```
- name: subnet-1
    zone: eu-es-2
  - name: subnet-2
  - name: subnet-3
  - name: subnet-4
  - name: subnet-5
    zone: eu-es-2
  - name: subnet-6
    zone: eu-es-1
  - name: subnet-7
```
The zone selection is done as below, considering index 0 -> Madrid 1, index 1 -> Madrid 2, index 2 -> Madrid 3

```
subnet 1 -> Madrid 2 (since zone is mentioned)
subnet 2 -> Madrid 2 (since index is 1)
subnet 3 -> Madrid 3 (since index is 2)
subnet 4 -> Madrid 1 (index % len(totalvpcZones)= 3%3= 0 so Madrid 1)
subnet 5 -> Madrid 2 (since zone is mentioned)
subnet 6 -> Madrid 1 (since zone is mentioned)
subnet 7 -> Madrid 1 (index % len(totalvpcZones)= 6%3= 0 so Madrid 1)
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1779 

**Special notes for your reviewer**:

/area provider/ibmcloud

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Review by Karthik-K-N — COMMENTED** [review]
How about handling this in webhooks, Having a default webhook which adds unique zone to subnets if it does not present.
Also I think we can error out if the user specifies more subnets than zone.

@dharaneeshvrd will there be any uses cases of user setting more subnets? like vpc region has 2 zones but user wants to create 4 subnets?

**Comment by dharaneeshvrd** [comment]
>will there be any uses cases of user setting more subnets? like vpc region has 2 zones but user wants to create 4 subnets?
its possible, we can just round robin the zones once subnets created for all zones.
i.e. consider the region has 2 zones, 10.241.0.0/24 is already used for subnet 1 for subnet 3, it automatically picks 10.241.1.0/24.

File: cloud/scope/powervs_cluster.go [hunk 1]
```diff
@@ -1105,8 +1105,27 @@ func (s *PowerVSClusterScope) ReconcileVPCSubnets() (bool, error) {
...
 	}
-	for _, subnet := range subnets {
-		s.Info("Reconciling VPC subnet", "subnet", subnet)
+	powerVSZone := s.Zone()
+	if powerVSZone == nil {
+		return false, fmt.Errorf("powervs zone is not set")
+	}
+	region := endpoints.ConstructRegionFromZone(*powerVSZone)
+	vpcZones, err := genUtil.VPCZonesForPowerVSRegion(region)
+	if err != nil {
```
Comment (Karthik-K-N) [inline cloud/scope/powervs_cluster.go:1114]: I know its in WIP but came across this, You can now derive vpc zone from vpc region instead of Power VS zone, For reference https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1819

Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster.go:1114]: Yeah sure I am rebasing my PR with latest changes.

**Comment by Shilpa-Gokul** [comment]
Tested the following scenarios

Case 1: When user provides more subnets than the available vpczones and provides no zone information with each subnet (subnets are created in the available vpc zones in a round robin method)
```
vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet
  - name: capi-test-cluster-sg-vpcsubnet-1
  - name: capi-test-cluster-sg-vpcsubnet-2
  - name: capi-test-cluster-sg-vpcsubnet-3
  - name: capi-test-cluster-sg-vpcsubnet-4
  - name: capi-test-cluster-sg-vpcsubnet-5
  - name: capi-test-cluster-sg-vpcsubnet-6
  zone: mad02
```
image (4)

Case 2: When user provides 2 subnets in the same zone to be created
```
 vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
    zone: eu-es-2
  - name: capi-test-cluster-sg-vpcsubnet-2
    zone: eu-es-2
```
image (2)

Case 3: User provides 1 subnet and the zone to be created in
```
 vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
    zone: eu-es-2
```
image (3)

Case 4: When user provides already created subnet
```
vpc:
  name: capi-test-cluster-sg-vpc-new
  region: eu-es
vpcSubnets:
- name: sn-20240723-01
zone: mad02
```
Log- [manager] I0723 12:15:38.121366       1 powervs_cluster.go:1103] "VPC subnet ID is set, fetching details" controller="ibmpowervscluster" controllerGroup="[infrastructure.cluster.x-k8s.io](http://infrastructure.cluster.x-k8s.io/)" controllerKind="IBMPowerVSCluster" IBMPowerVSCluster="default/capi-test-cluster-sg" namespace="default" name="capi-test-cluster-sg" reconcileID="19a61637-59a3-4ea0-896f-6bb3a4616902" cluster="default/capi-test-cluster-sg" id="02w7-e123549e-4414-480c-b018-7017492889b3"

Case 5: When user provides subnets with no zone information
```
vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
  - name: capi-test-cluster-sg-vpcsubnet-2
  zone: mad02
``` 
image (6)

@Karthik-K-N @Amulyam24 Please check this and let me know if I have to test anything else

**Comment by Karthik-K-N** [comment]
Since you are on this please take a look at this as well https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/1779#issuecomment-2378449066

**Comment by Shilpa-Gokul** [comment]
@Karthik-K-N I have used TotalIpv4AddressCount instead of Ipv4CIDRBlock for creating vpc subnet to be in sync with the vpc code. Both seems to do the same job, just that its easy to understand the number of ip addresses a subnet will have with the TotalIpv4AddressCount rather than calculating it with Ipv4CIDRBlock.

Verified the following usecases with the latest change. Please check and let me know if I need to test any other scenarios.
### Usecase 1- When the user provide more subnets than the available vpc zones
**Input:**
```Input: 
vpc:
    name: capi-test-cluster-sg-vpc
    region: eu-es
  vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
  - name: capi-test-cluster-sg-vpcsubnet-2
  - name: capi-test-cluster-sg-vpcsubnet-3
  - name: capi-test-cluster-sg-vpcsubnet-4
  zone: mad02
```
**Output:**
```
I1028 13:36:03.854799      14 ibmpowervscluster_controller.go:191] "Reconciling VPC subnets" logger="vpc" controller="ibmpowervscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="IBMPowerVSCluster" IBMPowerVSCluster="default/capi-test-cluster-sg" namespace="default" name="capi-test-cluster-sg" reconcileID="48e3c68b-1e8f-4caf-bfd0-880455627211" cluster="default/capi-test-cluster-sg"
E1028 13:36:03.855044      14 ibmpowervscluster_controller.go:193] "failed to reconcile VPC subnets" err="error validating input, total vpc subnets to be created cannot be more than the available vpc zones. subnets-4, vpczones 3" logger="vpc" controller="ibmpowervscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="IBMPowerVSCluster" IBMPowerVSCluster="default/capi-test-cluster-sg" namespace="default" name="capi-test-cluster-sg" reconcileID="48e3c68b-1e8f-4caf-bfd0-880455627211" cluster="default/capi-test-cluster-sg"
```
### Usecase 2- When user provides a single subnetName along with zone
**Input:**
 ```
vpc:
    name: capi-test-cluster-sg-vpc
    region: eu-es
  vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
    zone: eu-es-2
  zone: mad02
```
**Output:**
Subnets for VPC

### Usecase 3- When user provides subnets equal to the available vpc zones

Input:
```
vpc:
    name: capi-test-cluster-sg-vpc
    region: eu-es
  vpcSubnets:
  - name: capi-test-cluster-sg-vpcsubnet-1
  - name: capi-test-cluster-sg-vpcsubnet-2
  - name: capi-test-cluster-sg-vpcsubnet-3
  zone: mad02
```
Output:
Pasted Graphic 1

### Usecase 4- When user provides no vpcsubnets, subnets are created in each available zone
**Input:**
```
vpc:
    name: capi-test-cluster-sg-vpc
    region: eu-es
  zone: mad02
```
**Output:**
Pasted Graphic 2

**Comment by Karthik-K-N** [comment]
Thanks for the detailed explaination, For usecase1 can we use webhooks to validate?

**Comment by Shilpa-Gokul** [comment]
> Thanks for the detailed explaination, For usecase1 can we use webhooks to validate?

Added the validation in the webhook itself, below is the error response
```
The IBMPowerVSCluster "capi-test-cluster-sg" is invalid: : Invalid value: "spec.vpcSubnets": eu-es vpc region supports only 3 subnets but 4 subnets were provided
shilpagokul@Shilpas-MacBook-Pro templates %
```

**Comment by Shilpa-Gokul** [comment]
@Karthik-K-N @Prajyot-Parab Addressed all changes suggested, could you please review this PR? Also the checks are in pending state for so many days, retesting is also not working. could you please help on that as well?

File: api/v1beta2/ibmpowervscluster_webhook.go [hunk 2]
```diff
@@ -153,6 +153,22 @@ func (r *IBMPowerVSCluster) validateIBMPowerVSClusterVPCSubnetNames() (allErrs f
 	return allErrs
 }
 
+func (r *IBMPowerVSCluster) validateIBMPowerVSClusterVPCSubnets() (allErrs field.ErrorList) {
+	if err := r.validateIBMPowerVSClusterVPCSubnetNames(); err != nil {
+		allErrs = append(allErrs, err...)
+	}
+
+	vpcZones, err := regionUtil.VPCZonesForVPCRegion(*r.Spec.VPC.Region)
```
Comment (Karthik-K-N) [inline api/v1beta2/ibmpowervscluster_webhook.go:161]: VPC can be nil, Ref PR https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/2038, Safe to add checks

File: api/v1beta2/ibmpowervscluster_webhook.go [hunk 3]
```diff
@@ -153,6 +153,22 @@ func (r *IBMPowerVSCluster) validateIBMPowerVSClusterVPCSubnetNames() (allErrs f
...
+	if err != nil {
+		ibmpowervsclusterlog.Error(fmt.Errorf("error fetching vpc zones"), err.Error())
```
Comment (Karthik-K-N) [inline api/v1beta2/ibmpowervscluster_webhook.go:163]:
```suggestion
		ibmpowervsclusterlog.Error(fmt.Errorf("error validating vpc zones"), err.Error())
```

File: api/v1beta2/ibmpowervscluster_webhook.go [hunk 4]
```diff
@@ -209,7 +225,7 @@ func (r *IBMPowerVSCluster) validateIBMPowerVSClusterCreateInfraPrereq() (allErr
 	if r.Spec.ResourceGroup == nil {
 		allErrs = append(allErrs, field.Invalid(field.NewPath("spec.resourceGroup"), r.Spec.ResourceGroup, "value of resource group is empty"))
 	}
-	if err := r.validateIBMPowerVSClusterVPCSubnetNames(); err != nil {
```
Comment (Karthik-K-N) [inline api/v1beta2/ibmpowervscluster_webhook.go:212]: We also need to validated duplicate subnet names right?

File: cloud/scope/powervs_cluster.go [hunk 5]
```diff
@@ -1198,42 +1205,26 @@ func (s *PowerVSClusterScope) createVPCSubnet(subnet infrav1beta2.Subnet) (*stri
...
 	if vpcID == nil {
 		return nil, fmt.Errorf("VPC ID is empty")
 	}
-	cidrBlock, err := s.IBMVPCClient.GetSubnetAddrPrefix(*vpcID, zone)
-	if err != nil {
-		return nil, err
-	}
-	ipVersion := "ipv4"
+
+	var ipCount int64 = 256
```
Comment (Karthik-K-N) [inline cloud/scope/powervs_cluster.go:1215]: Can we move this to constants for now with comments?

File: api/v1beta2/ibmpowervscluster_webhook.go (hunk 4 above)
Comment (Shilpa-Gokul) [reply api/v1beta2/ibmpowervscluster_webhook.go:212]: I have added it here already- https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/76b57c8aeb9256bbb66b3a5a01779ec4c9934a71/api/v1beta2/ibmpowervscluster_webhook.go#L156-L158

File: cloud/scope/powervs_cluster.go (hunk 5 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster.go]: Done

File: api/v1beta2/ibmpowervscluster_webhook.go (hunk 2 above)
Comment (Shilpa-Gokul) [reply api/v1beta2/ibmpowervscluster_webhook.go]: Done

**Comment by dharaneeshvrd** [comment]
@Shilpa-Gokul what happens with this case?
`Case 2: When user provides 2 subnets in the same zone to be created`

File: cloud/scope/powervs_cluster.go [hunk 6]
```diff
@@ -74,7 +74,12 @@ var (
 )
 
 // powerEdgeRouter is identifier for PER.
-const powerEdgeRouter = "power-edge-router"
+const (
+	powerEdgeRouter = "power-edge-router"
+	// vpcSubnetIPAddressCount is the total IP Addresses for the subnet. Until support for custom
+	// address prefixes is added, we use the ip count for subnet creation.
```
Comment (Prajyot-Parab) [inline cloud/scope/powervs_cluster.go:80]:
```suggestion
	// vpcSubnetIPAddressCount is the total IP Addresses for the subnet.
	// Support for custom address prefixes will be added at a later time. Currently, we use the ip count for subnet creation.
```

File: cloud/scope/powervs_cluster.go [hunk 7]
```diff
@@ -1198,42 +1210,25 @@ func (s *PowerVSClusterScope) createVPCSubnet(subnet infrav1beta2.Subnet) (*stri
...
-		}
-		zone = vpcZones[0]
-	}
 
 	// create subnet
 	vpcID := s.GetVPCID()
 	if vpcID == nil {
 		return nil, fmt.Errorf("VPC ID is empty")
 	}
-	cidrBlock, err := s.IBMVPCClient.GetSubnetAddrPrefix(*vpcID, zone)
```
Comment (Prajyot-Parab) [inline cloud/scope/powervs_cluster.go:1221]: You also need to remove the function definitions as well, if they are not being used anywhere else.

File: cloud/scope/powervs_cluster.go [hunk 8]
```diff
@@ -1172,7 +1181,10 @@ func (s *PowerVSClusterScope) ReconcileVPCSubnets() (bool, error) {
 		}
 		s.Info("Created VPC subnet", "subnetID", subnetID)
 		s.SetVPCSubnetStatus(*subnet.Name, infrav1beta2.ResourceReference{ID: subnetID, ControllerCreated: ptr.To(true)})
-		return true, nil
+		// Requeue only when all subnets' creation are triggered
```
Comment (Prajyot-Parab) [inline cloud/scope/powervs_cluster.go:1184]:
```suggestion
		// Requeue only when all subnets creation are triggered
```

Comment (Prajyot-Parab) [inline cloud/scope/powervs_cluster.go:1184]:
```suggestion
		// Requeue only when the creation of all subnets has been triggered.
```

**Comment by Shilpa-Gokul** [comment]
> @Shilpa-Gokul what happens with this case? `Case 2: When user provides 2 subnets in the same zone to be created` I think we probably need to add a validation to not to allow dup zones, it would cause collision with ip range with current code I guess.

@dharaneeshvrd  Have added validation to return error as shown below
```
cluster.cluster.x-k8s.io/capi-test-cluster-sg created
The IBMPowerVSCluster "capi-test-cluster-sg" is invalid: spec.vpcSubnets[1]: Duplicate value: map[string]interface {}{"Zone":"eu-es-2"}
```

File: cloud/scope/powervs_cluster.go (hunk 8 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster.go]: Addressed

File: cloud/scope/powervs_cluster.go (hunk 7 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster.go:1221]: Removed this function definition and declaration since its not used anywhere else

**Review by dharaneeshvrd — COMMENTED** [review]
What happens to this case?
```
vpcSubnets:
  - name: subnet-1
    zone: eu-es-2
  - name: subnet-2
```
Again it will get a collision I guess, since we are not handling the combination of both user provided and not provided. 
Please handle this as well and if you can add UT with different corner cases that would be good for `ReconcileVPCSubnets`.

**Comment by Shilpa-Gokul** [comment]
Currently when we use vpcSubnetIPAddressCount, when two subnets are to be created in the same zone, the subnets are created with the next available address prefix based on the vpcSubnetIPAddressCount.
When no zones are mentioned, the subnets are assigned to the zones in round robin method.
Taking one of the below examples for reference
```
- name: subnet-1
    zone: eu-es-2
  - name: subnet-2
  - name: subnet-3
  - name: subnet-4
  - name: subnet-5
    zone: eu-es-2
  - name: subnet-6
    zone: eu-es-1
  - name: subnet-7
```

The zone selection is done as below, considering index 0 -> Madrid 1, index 1 -> Madrid 2, index 2 -> Madrid 3
```
subnet 1 -> Madrid 2 (since zone is mentioned)
subnet 2 -> Madrid 2 (since index is 1)
subnet 3 -> Madrid 3 (since index is 2)
subnet 4 -> Madrid 1 (index % len(totalvpcZones)= 3%3= 0 so Madrid 1)
subnet 5 -> Madrid 2 (since zone is mentioned)
subnet 6 -> Madrid 1 (since zone is mentioned)
subnet 7 -> Madrid 1 (index % len(totalvpcZones)= 6%3= 0 so Madrid 1)
```

Tested the following scenarios.
 
### Usecase 1: When user provides more subnets than the available VPC zones and also mentions zone for one subnet
```
vpcSubnets:
  - name: subnet-1
    zone: eu-es-2
  - name: subnet-2
  - name: subnet-3
  - name: subnet-4
  - name: subnet-5
zone: mad02
```
Pasted Graphic

### Usecase 2: When user provides subnets more than the available VPC zones and mentions zone randomly for few subnets
  ```
vpcSubnets:
  - name: subnet-1
    zone: eu-es-2
  - name: subnet-2
  - name: subnet-3
  - name: subnet-4
  - name: subnet-5
    zone: eu-es-2
  - name: subnet-6
    zone: eu-es-1
  - name: subnet-7
zone: mad02
```
Pasted Graphic 1

### Usecase 3: When user provides subnets less than the available VPC zones along with zone specified for each subnet
```
vpcSubnets:
  - name: subnet-1
    zone: eu-es-2
  - name: subnet-2
    zone: eu-es-1
zone: mad02
```
Pasted Graphic 2

### Usecase 4: When user provides already existing subnet
```
 vpcSubnets:
  - name: eu-es-1-default-subnet
    zone: eu-es-1
 zone: mad02
```

`I1125 13:27:02.827412      14 powervs_cluster.go:1167] "Found VPC subnet in IBM Cloud" controller="ibmpowervscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="IBMPowerVSCluster" IBMPowerVSCluster="default/capi-test-cluster-sg" namespace="default" name="capi-test-cluster-sg" reconcileID="20586ea8-2019-4770-97bd-81cd925624f4" cluster="default/capi-test-cluster-sg" subnetID="02w7-5e7172ea-8306-444f-b4e6-97acbf35f530"`

### Usecase 5: When user specifies subnets more than the available VPC zones with no zones mentioned
```
 vpcSubnets:
  - name: subnet1
  - name: subnet2
  - name: subnet3
  - name: subnet4
  - name: subnet5
  - name: subnet6
zone: mad02
```
Subnets for VPC

### Usecase 6: When user doesn't provide any subnets explicitly, a subnet is created in each available VPC zone
```
 vpc:
    name: capi-test-cluster-sg-vpc
    region: eu-es
  zone: mad02
```
Pasted Graphic 4

File: api/v1beta2/ibmpowervscluster_webhook.go [hunk 9]
```diff
@@ -209,7 +216,7 @@ func (r *IBMPowerVSCluster) validateIBMPowerVSClusterCreateInfraPrereq() (allErr
...
+	if err := r.validateIBMPowerVSClusterVPCSubnets(); err != nil {
```
Comment (Karthik-K-N) [inline api/v1beta2/ibmpowervscluster_webhook.go:219]: Since we are only validating the subnet name duplication, Can we revert back to old change? Can we directly call validateIBMPowerVSClusterVPCSubnetNames() from here?

File: cloud/scope/powervs_cluster.go [hunk 10]
```diff
@@ -1102,13 +1107,14 @@ func (s *PowerVSClusterScope) createVPC() (*string, error) {
...
+	}
 	// check whether user has set the vpc subnets
 	if len(s.IBMPowerVSCluster.Spec.VPCSubnets) == 0 {
 		// if the user did not set any subnet, we try to create subnet in all the zones.
-		vpcZones, err := regionUtil.VPCZonesForVPCRegion(*s.VPC().Region)
-		if err != nil {
-			return false, err
-		}
+
 		if len(vpcZones) == 0 {
```
Comment (Karthik-K-N) [inline cloud/scope/powervs_cluster.go:1118]: I think we should move this check right after we fetch teh vpcZones? so we can early return?

File: api/v1beta2/ibmpowervscluster_webhook.go [hunk 11]
```diff
@@ -138,21 +138,28 @@ func (r *IBMPowerVSCluster) validateIBMPowerVSClusterLoadBalancerNames() (allErr
 }
 
 func (r *IBMPowerVSCluster) validateIBMPowerVSClusterVPCSubnetNames() (allErrs field.ErrorList) {
-	found := make(map[string]bool)
+	subnetFound := make(map[string]bool)
```
Comment (dharaneeshvrd) [inline api/v1beta2/ibmpowervscluster_webhook.go:141]: I think you can revert this.

File: cloud/scope/powervs_cluster.go [hunk 12]
```diff
@@ -1164,6 +1170,13 @@ func (s *PowerVSClusterScope) ReconcileVPCSubnets() (bool, error) {
 			continue
 		}
 
+		if subnet.Zone == nil {
+			if index < len(vpcZones) {
```
Comment (dharaneeshvrd) [inline cloud/scope/powervs_cluster.go:1174]: You can directly use `vpcZones[index%len(vpcZones)]` logic, no need of this.

**Review by dharaneeshvrd — COMMENTED** [review]
Can you please add a UT for index rotating logic as well?

File: cloud/scope/powervs_cluster.go (hunk 10 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster.go]: Sure, I have moved it now

File: api/v1beta2/ibmpowervscluster_webhook.go (hunk 9 above)
Comment (Shilpa-Gokul) [reply api/v1beta2/ibmpowervscluster_webhook.go]: Done

**Review by Karthik-K-N — COMMENTED** [review]
This has been one of the difficult feature to implement and it has gone through lots of iteration during implementation as well, Thanks @Shilpa-Gokul for take care of this. Appreciate your commitment and ownership on this feature.

/lgtm
/assign @dharaneeshvrd

File: cloud/scope/powervs_cluster_test.go [hunk 13]
```diff
@@ -3581,7 +3731,7 @@ func TestSetVPCSubnetStatus(t *testing.T) {
 					Status: infrav1beta2.IBMPowerVSClusterStatus{
 						VPCSubnet: map[string]infrav1beta2.ResourceReference{
 							"subnet1Name": {
-								ControllerCreated: ptr.To(false),
+								ControllerCreated: ptr.To(true),
```
Comment (dharaneeshvrd) [inline cloud/scope/powervs_cluster_test.go:3734]: nit: why we need this change?

File: cloud/scope/powervs_cluster_test.go [hunk 14]
```diff
@@ -3571,7 +3721,7 @@ func TestSetVPCSubnetStatus(t *testing.T) {
 			clusterScope: PowerVSClusterScope{
 				IBMPowerVSCluster: &infrav1beta2.IBMPowerVSCluster{},
 			},
-			resource: infrav1beta2.ResourceReference{ID: ptr.To("ID1")},
+			resource: infrav1beta2.ResourceReference{ID: ptr.To("ID12")},
```
Comment (dharaneeshvrd) [inline cloud/scope/powervs_cluster_test.go:3724]: nit: why we need this change?

**Review by dharaneeshvrd — COMMENTED** [review]
Just few nits.
Overall LGTM!

File: cloud/scope/powervs_cluster_test.go (hunk 13 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster_test.go:3734]: Not required, have reverted

File: cloud/scope/powervs_cluster_test.go (hunk 14 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster_test.go]: Not really required, have reverted

File: cloud/scope/powervs_cluster_test.go (hunk 13 above)
Comment (Shilpa-Gokul) [reply cloud/scope/powervs_cluster_test.go:3734]: I had to cover the case where the controllercreated value is true- https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/48777461bd36a5ca27d61ffc6e83af5163ae95f6/cloud/scope/powervs_cluster.go#L529

**Review by dharaneeshvrd — COMMENTED** [review]
/lgtm

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm
Thanks @Shilpa-Gokul

**Comment by mkumatag** [comment]
Thanks @Shilpa-Gokul for fixing this, it was a tricky one to solve.

**Comment by Shilpa-Gokul** [comment]
@mkumatag @Karthik-K-N @Amulyam24 @Prajyot-Parab @dharaneeshvrd Thanks to you all for helping me understand the codebase, different usecases and scenarios
